[package]
name = "han-speech"
version = "0.1.0"
authors = ["Luozijun <luozijun.assistant@gmail.com>"]


[dependencies]
rand = "0.5.5"

[dev-dependencies]
# rusty-machine = "0.5.4"

[target.'cfg(target_os = "macos")'.dependencies]
coreaudio-rs = "0.9.1"
